// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package connector_paradym.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class SplitJoin extends CustomJavaAction<java.lang.String>
{
	private java.lang.String string;
	private java.lang.String regex;
	private java.lang.String joint;

	public SplitJoin(IContext context, java.lang.String string, java.lang.String regex, java.lang.String joint)
	{
		super(context);
		this.string = string;
		this.regex = regex;
		this.joint = joint;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return(String.join(joint,string.split(regex)));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SplitJoin";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
